'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TTRM.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About....
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A multi-tracker and forums registration availability tool through Selenium API..
        '''</summary>
        Friend Shared ReadOnly Property AboutDescriptionText() As String
            Get
                Return ResourceManager.GetString("AboutDescriptionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow plugins to notify about open application forms.
        '''</summary>
        Friend Shared ReadOnly Property AllowPluginsToCheckApplicationForms() As String
            Get
                Return ResourceManager.GetString("AllowPluginsToCheckApplicationForms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application cache has been fully cleaned..
        '''</summary>
        Friend Shared ReadOnly Property ApplicationCacheHasBeenCleaned() As String
            Get
                Return ResourceManager.GetString("ApplicationCacheHasBeenCleaned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application page.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationPageMenuItem() As String
            Get
                Return ResourceManager.GetString("ApplicationPageMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatic Plugin Execution.
        '''</summary>
        Friend Shared ReadOnly Property AutoPluginRunGroupBox() As String
            Get
                Return ResourceManager.GetString("AutoPluginRunGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run selected plugins every:.
        '''</summary>
        Friend Shared ReadOnly Property AutoPluginRunMsg() As String
            Get
                Return ResourceManager.GetString("AutoPluginRunMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⛔ Automatic plugins execution timer disabled..
        '''</summary>
        Friend Shared ReadOnly Property AutoPluginRunTimerDisabled() As String
            Get
                Return ResourceManager.GetString("AutoPluginRunTimerDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ✔️ Automatic plugins execution timer enabled..
        '''</summary>
        Friend Shared ReadOnly Property AutoPluginRunTimerEnabled() As String
            Get
                Return ResourceManager.GetString("AutoPluginRunTimerEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⬛ {0} of {1}.
        '''</summary>
        Friend Shared ReadOnly Property AutoRunPluginCheckedAllFormat() As String
            Get
                Return ResourceManager.GetString("AutoRunPluginCheckedAllFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🗹 {0} of {1}.
        '''</summary>
        Friend Shared ReadOnly Property AutoRunPluginCheckedCountFormat() As String
            Get
                Return ResourceManager.GetString("AutoRunPluginCheckedCountFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ☐ 0 of {0}.
        '''</summary>
        Friend Shared ReadOnly Property AutoRunPluginCheckedNoneFormat() As String
            Get
                Return ResourceManager.GetString("AutoRunPluginCheckedNoneFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot navigate to the specified URL. Reason: {0}.
        '''</summary>
        Friend Shared ReadOnly Property CantNavigateToUrlFormat() As String
            Get
                Return ResourceManager.GetString("CantNavigateToUrlFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot establish a connection to the specified URL. HTTP Status Code: {0}.
        '''</summary>
        Friend Shared ReadOnly Property CantStablishConnectionFormat() As String
            Get
                Return ResourceManager.GetString("CantStablishConnectionFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear cache.
        '''</summary>
        Friend Shared ReadOnly Property ClearCache() As String
            Get
                Return ResourceManager.GetString("ClearCache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🧹  Clearing application cache....
        '''</summary>
        Friend Shared ReadOnly Property ClearingApplicationCacheMsg() As String
            Get
                Return ResourceManager.GetString("ClearingApplicationCacheMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🧹  Clearing plugin&apos;s cache....
        '''</summary>
        Friend Shared ReadOnly Property ClearingPluginCacheMsg() As String
            Get
                Return ResourceManager.GetString("ClearingPluginCacheMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear previous log entries on plugin execution.
        '''</summary>
        Friend Shared ReadOnly Property ClearPreviousLogEntries() As String
            Get
                Return ResourceManager.GetString("ClearPreviousLogEntries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear selection.
        '''</summary>
        Friend Shared ReadOnly Property ClearSelectedPlugins() As String
            Get
                Return ResourceManager.GetString("ClearSelectedPlugins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close application.
        '''</summary>
        Friend Shared ReadOnly Property CloseApplication() As String
            Get
                Return ResourceManager.GetString("CloseApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current URL loaded in the web browser does not match the URL expected by the plugin.
        '''</summary>
        Friend Shared ReadOnly Property CurrentBrowserUrlDiffersFromPluginUrl() As String
            Get
                Return ResourceManager.GetString("CurrentBrowserUrlDiffersFromPluginUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Don&apos;t run selected plugins if an application is in fullscreen mode.
        '''</summary>
        Friend Shared ReadOnly Property DontRunIfFullscreen() As String
            Get
                Return ResourceManager.GetString("DontRunIfFullscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicated plugins with the same name have been found. Only the first plugin will be loaded..
        '''</summary>
        Friend Shared ReadOnly Property DuplicatedPluginsDetected() As String
            Get
                Return ResourceManager.GetString("DuplicatedPluginsDetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Error executing dynamic code: {0}.
        '''</summary>
        Friend Shared ReadOnly Property DynamicCodeExecutionErrorFormat() As String
            Get
                Return ResourceManager.GetString("DynamicCodeExecutionErrorFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Dynamic Code Compilation Errors:.
        '''</summary>
        Friend Shared ReadOnly Property DynamicCompilationErrors() As String
            Get
                Return ResourceManager.GetString("DynamicCompilationErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable paralell execution.
        '''</summary>
        Friend Shared ReadOnly Property EnableParalellExecution() As String
            Get
                Return ResourceManager.GetString("EnableParalellExecution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Error loading plugin file &apos;{0}&apos;: {1}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadingPluginFormat() As String
            Get
                Return ResourceManager.GetString("ErrorLoadingPluginFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⚙️ Running plugin....
        '''</summary>
        Friend Shared ReadOnly Property ExecutingPlugin() As String
            Get
                Return ResourceManager.GetString("ExecutingPlugin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⚙️ Running plugins....
        '''</summary>
        Friend Shared ReadOnly Property ExecutingPluginsTooltip() As String
            Get
                Return ResourceManager.GetString("ExecutingPluginsTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A plugin is currently running. Do you really want to exit now?. 
        '''
        '''Press NO to wait until the plugin execution ends.
        '''
        '''Press YES to exit, forcefully terminating any Chrome-related child processes..
        '''</summary>
        Friend Shared ReadOnly Property FormCloseWarningPluginWorkInProgress() As String
            Get
                Return ResourceManager.GetString("FormCloseWarningPluginWorkInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application.
        '''</summary>
        Friend Shared ReadOnly Property GroupBoxApplication() As String
            Get
                Return ResourceManager.GetString("GroupBoxApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide window.
        '''</summary>
        Friend Shared ReadOnly Property HideWindow() As String
            Get
                Return ResourceManager.GetString("HideWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hours.
        '''</summary>
        Friend Shared ReadOnly Property Hours() As String
            Get
                Return ResourceManager.GetString("Hours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The IWebDriver instance must support javascript execution..
        '''</summary>
        Friend Shared ReadOnly Property IWebDriverMustSupportJavascriptExecution() As String
            Get
                Return ResourceManager.GetString("IWebDriverMustSupportJavascriptExecution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property LanguageLabel() As String
            Get
                Return ResourceManager.GetString("LanguageLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 💡 Press the main button to run the plugin..
        '''</summary>
        Friend Shared ReadOnly Property LastPluginRunInitialText() As String
            Get
                Return ResourceManager.GetString("LastPluginRunInitialText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last plugin execution on {0} at {1} hours..
        '''</summary>
        Friend Shared ReadOnly Property LastPluginRunMsgFormat() As String
            Get
                Return ResourceManager.GetString("LastPluginRunMsgFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login page.
        '''</summary>
        Friend Shared ReadOnly Property LoginPageMenuItem() As String
            Get
                Return ResourceManager.GetString("LoginPageMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Error: No class of type DynamicPlugin was found in the plugin&apos;s source code..
        '''</summary>
        Friend Shared ReadOnly Property MissingDynamicPluginClass() As String
            Get
                Return ResourceManager.GetString("MissingDynamicPluginClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Error: No method with name RunAsync was found in the plugin&apos;s source code..
        '''</summary>
        Friend Shared ReadOnly Property MissingRunAsyncMethod() As String
            Get
                Return ResourceManager.GetString("MissingRunAsyncMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Error: No plugins are available inside the &apos;plugins&apos; folder..
        '''</summary>
        Friend Shared ReadOnly Property NoPluginsAvailable() As String
            Get
                Return ResourceManager.GetString("NoPluginsAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open release page.
        '''</summary>
        Friend Shared ReadOnly Property OpenGitHubLatestReleasePage() As String
            Get
                Return ResourceManager.GetString("OpenGitHubLatestReleasePage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Website.
        '''</summary>
        Friend Shared ReadOnly Property OpenWebsiteButton() As String
            Get
                Return ResourceManager.GetString("OpenWebsiteButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plugin&apos;s cache has been fully cleaned..
        '''</summary>
        Friend Shared ReadOnly Property PluginCacheHasBeenCleaned() As String
            Get
                Return ResourceManager.GetString("PluginCacheHasBeenCleaned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plugins.
        '''</summary>
        Friend Shared ReadOnly Property Plugins() As String
            Get
                Return ResourceManager.GetString("Plugins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program.
        '''</summary>
        Friend Shared ReadOnly Property Program() As String
            Get
                Return ResourceManager.GetString("Program", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new version of the program is available..
        '''</summary>
        Friend Shared ReadOnly Property ProgramUpdateAvailable() As String
            Get
                Return ResourceManager.GetString("ProgramUpdateAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration page.
        '''</summary>
        Friend Shared ReadOnly Property RegistrationPageMenuItem() As String
            Get
                Return ResourceManager.GetString("RegistrationPageMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember current settings.
        '''</summary>
        Friend Shared ReadOnly Property RememberSettings() As String
            Get
                Return ResourceManager.GetString("RememberSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run selected plugins now.
        '''</summary>
        Friend Shared ReadOnly Property RunAllSelectedPluginsNow() As String
            Get
                Return ResourceManager.GetString("RunAllSelectedPluginsNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run application minimized to system-tray.
        '''</summary>
        Friend Shared ReadOnly Property RunAppMinimized() As String
            Get
                Return ResourceManager.GetString("RunAppMinimized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run plugin.
        '''</summary>
        Friend Shared ReadOnly Property RunPluginButton() As String
            Get
                Return ResourceManager.GetString("RunPluginButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search program updates.
        '''</summary>
        Friend Shared ReadOnly Property SearchProgramUpdates() As String
            Get
                Return ResourceManager.GetString("SearchProgramUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select all.
        '''</summary>
        Friend Shared ReadOnly Property SelectAllPlugins() As String
            Get
                Return ResourceManager.GetString("SelectAllPlugins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show window.
        '''</summary>
        Friend Shared ReadOnly Property ShowWindow() As String
            Get
                Return ResourceManager.GetString("ShowWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only one instance of the program is allowed..
        '''</summary>
        Friend Shared ReadOnly Property SingleInstanceMsg() As String
            Get
                Return ResourceManager.GetString("SingleInstanceMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⚙️ Analyzing page content....
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_AnalyzingPageContent() As String
            Get
                Return ResourceManager.GetString("StatusMsg_AnalyzingPageContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ✅ Application page loaded..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_ApplicationPageLoaded() As String
            Get
                Return ResourceManager.GetString("StatusMsg_ApplicationPageLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ✅ Cloudflare challenge completed..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_CloudflareChallengeCompleted() As String
            Get
                Return ResourceManager.GetString("StatusMsg_CloudflareChallengeCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cloudflare challenge has timed out (cf_clearance cookie could not be validated)..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_CloudflareChallengeTimedOut() As String
            Get
                Return ResourceManager.GetString("StatusMsg_CloudflareChallengeTimedOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⌛ Waiting to complete Cloudflare challenge....
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_CloudflareChallengeWait() As String
            Get
                Return ResourceManager.GetString("StatusMsg_CloudflareChallengeWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🌐 Connecting to {0} website....
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_ConnectingFormat() As String
            Get
                Return ResourceManager.GetString("StatusMsg_ConnectingFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🚫 Application form is closed..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_DetectedApplicationClosed() As String
            Get
                Return ResourceManager.GetString("StatusMsg_DetectedApplicationClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🎉 Application form is open..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_DetectedApplicationOpen() As String
            Get
                Return ResourceManager.GetString("StatusMsg_DetectedApplicationOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🚫 Registration form is closed..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_DetectedRegClosed() As String
            Get
                Return ResourceManager.GetString("StatusMsg_DetectedRegClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🎉 Registration form is open..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_DetectedRegOpen() As String
            Get
                Return ResourceManager.GetString("StatusMsg_DetectedRegOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The HTML content is still changing (the dynamic DOM updates did not complete within the time out)..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_DomChangesTimedOut() As String
            Get
                Return ResourceManager.GetString("StatusMsg_DomChangesTimedOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ Error: {0}.
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_ExceptionFormat() As String
            Get
                Return ResourceManager.GetString("StatusMsg_ExceptionFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ❌ There was an error during the last plugin run: {0}.
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_ExceptionMessageBoxFormat() As String
            Get
                Return ResourceManager.GetString("StatusMsg_ExceptionMessageBoxFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ✅ Login page loaded..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_LoginPageLoaded() As String
            Get
                Return ResourceManager.GetString("StatusMsg_LoginPageLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🎉 The application form is now open on {0}! You can apply for an account now. 😃.
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_MsgboxApplicationOpenFormat() As String
            Get
                Return ResourceManager.GetString("StatusMsg_MsgboxApplicationOpenFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🎉 The registration form is now open on {0}! You can create an account now. 😃.
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_MsgboxRegOpenFormat() As String
            Get
                Return ResourceManager.GetString("StatusMsg_MsgboxRegOpenFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network is not available..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_NetworkIsNotAvailable() As String
            Get
                Return ResourceManager.GetString("StatusMsg_NetworkIsNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 🧹 Closing browser. Operation completed..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_OperationCompleted() As String
            Get
                Return ResourceManager.GetString("StatusMsg_OperationCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The page source code is empty: &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_PageSourceEmptyFormat() As String
            Get
                Return ResourceManager.GetString("StatusMsg_PageSourceEmptyFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ➡️ Register button clicked..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_RegisterButtonClicked() As String
            Get
                Return ResourceManager.GetString("StatusMsg_RegisterButtonClicked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ✅ Register button found..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_RegisterButtonFound() As String
            Get
                Return ResourceManager.GetString("StatusMsg_RegisterButtonFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ✅ Registration page loaded..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_RegisterPageLoaded() As String
            Get
                Return ResourceManager.GetString("StatusMsg_RegisterPageLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The trigger phrase for the application form is empty..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_TriggerAppEmpty() As String
            Get
                Return ResourceManager.GetString("StatusMsg_TriggerAppEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The trigger phrase for the registration form is empty..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_TriggerRegEmpty() As String
            Get
                Return ResourceManager.GetString("StatusMsg_TriggerRegEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot navigate to the specified URL due an HTTP error code 404 (Not found)..
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_UrlNotfound404() As String
            Get
                Return ResourceManager.GetString("StatusMsg_UrlNotfound404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⚙️ Verifying page load requirements....
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_VerifyingPageLoadRequirements() As String
            Get
                Return ResourceManager.GetString("StatusMsg_VerifyingPageLoadRequirements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⏳ Waiting for the page to finish loading....
        '''</summary>
        Friend Shared ReadOnly Property StatusMsg_WaitingForPageLoad() As String
            Get
                Return ResourceManager.GetString("StatusMsg_WaitingForPageLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prevent the system from entering sleep mode.
        '''</summary>
        Friend Shared ReadOnly Property SystemSleepMsg() As String
            Get
                Return ResourceManager.GetString("SystemSleepMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The page load has timed out while the DOM was being updated..
        '''</summary>
        Friend Shared ReadOnly Property TimedOutDuringDynamicDOMUpdating() As String
            Get
                Return ResourceManager.GetString("TimedOutDuringDynamicDOMUpdating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The browser is currently running in headless mode. You must add the &quot;--headless&quot; argument when creating the ChromeDriver instance..
        '''</summary>
        Friend Shared ReadOnly Property UsingHeadlessChromeForCloudflareChallengeAttempt() As String
            Get
                Return ResourceManager.GetString("UsingHeadlessChromeForCloudflareChallengeAttempt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ⌛ Waiting {0} for the next automatic plugins execution....
        '''</summary>
        Friend Shared ReadOnly Property WaitingForTheNextAutomaticExecutionFormat() As String
            Get
                Return ResourceManager.GetString("WaitingForTheNextAutomaticExecutionFormat", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
